[en_GB]
ErrorFillIn = "Please fill out all fields that are marked red"
LoginFailure = "Your access data could not be assigned to a user"
LoginFailureActive = "Your customer account has been deactivated. Please contact us personally."
LoginFailureLocked = "Too many failed login attempts. Your account has been temporarily deactivated - Please try again in a few minutes!"
MailFailure = "Please enter a valid email address"
MailFailureAlreadyRegistered = "This email address is already registered"
MailFailureNotEqual = "The email addresses do not match"
NewsletterFailureAlreadyRegistered = "You are already subscribed to our newsletter"
NewsletterFailureInvalid = "Please enter a valid email address"
NewsletterFailureMail = "Please enter an email address"
NewsletterFailureNotFound = "This email address could not be found"
NewsletterMailDeleted = "Your email address has been deleted."
NewsletterSuccess = "Thank you! We have entered your address."
UnknownError = "An unknown error has occured."

[de_DE]
ErrorFillIn = "Bitte füllen Sie alle rot markierten Felder aus"
LoginFailure = "Ihre Zugangsdaten konnten keinem Benutzer zugeordnet werden"
LoginFailureActive = "Ihr Kundenkonto wurde deaktiviert, bitte wenden Sie sich zwecks Klärung persönlich an uns!"
LoginFailureLocked = "Zu viele fehlgeschlagene Versuche. Ihr Account wurde vorübergehend deaktiviert - bitte probieren Sie es in einigen Minuten erneut!"
MailFailure = "Bitte geben Sie eine gültige eMail-Adresse ein"
MailFailureAlreadyRegistered = "Diese eMail-Adresse ist bereits registriert"
MailFailureNotEqual = "Die eMail-Adressen stimmen nicht überein."
NewsletterFailureAlreadyRegistered = "Sie erhalten unseren Newsletter bereits"
NewsletterFailureInvalid = "Bitte geben Sie eine gültige eMail-Adresse ein"
NewsletterFailureMail = "Bitte geben sie eine eMail-Adresse an"
NewsletterFailureNotFound = "Diese eMail-Adresse wurde nicht gefunden"
NewsletterMailDeleted = "Ihre eMail-Adresse wurde gelöscht"
NewsletterSuccess = "Vielen Dank. Wir haben Ihre Adresse eingetragen."
UnknownError = "Ein unbekannter Fehler ist aufgetreten"

